apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: devopsproject
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
  selector:
    app: back