apiVersion: v1
kind: Service
metadata:
  name: back-db-cluster-ip-service
  namespace: devopsproject
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db