apiVersion: v1
kind: Service
metadata:
  namespace: devopsproject
  name: front-back-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: back