apiVersion: v1
kind: Service
metadata:
  namespace: devopsproject
  name: front-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
  selector:
    app: front